main: fr.joanteriihoania.peage.Main
name: Peage
version: '1.0'
author: Arcadia_sama
api-version: '1.15'
load: POSTWORLD
website: http://joan-teriihoania.fr/

commands:
  peage:
    description: Informations sur le plugin Peage
    usage: /<peage> [network|stand] [list|create|remove|edit|set] [...]

permissions:
  peage.admin:
    description: Autorise les commandes admin
    default: op

depend: [Vault]